"""
Event classes for the event-driven backtesting system.
Events are time-stamped and processed in chronological order using a priority queue.
"""

from enum import Enum
from datetime import datetime


class EventType(Enum):
    """Enumeration of different event types in the trading system."""
    MARKET = 1
    SIGNAL = 2
    ORDER = 3
    FILL = 4


class Event:
    """
    Base class for all events in the trading system.
    Events are comparable based on their timestamp for priority queue ordering.
    """
    
    def __init__(self, timestamp):
        """
        Initialize an Event.
        
        Args:
            timestamp: datetime object representing when the event occurs
        """
        self.type = None
        self.timestamp = timestamp
    
    def __lt__(self, other):
        """Compare events by timestamp for min-heap ordering."""
        return self.timestamp < other.timestamp
    
    def __le__(self, other):
        """Compare events by timestamp for min-heap ordering."""
        return self.timestamp <= other.timestamp
    
    def __repr__(self):
        return f"{self.__class__.__name__}(timestamp={self.timestamp})"


class MarketEvent(Event):
    """
    Represents new market data arriving (e.g., a new bar/candlestick).
    Contains price information for a given symbol at a specific time.
    """
    
    def __init__(self, timestamp, symbol, open_price, high, low, close, volume):
        """
        Initialize a MarketEvent.
        
        Args:
            timestamp: datetime when this market data is valid
            symbol: ticker symbol (e.g., 'AAPL')
            open_price: opening price for the period
            high: highest price during the period
            low: lowest price during the period
            close: closing price for the period
            volume: trading volume
        """
        super().__init__(timestamp)
        self.type = EventType.MARKET
        self.symbol = symbol
        self.open = open_price
        self.high = high
        self.low = low
        self.close = close
        self.volume = volume
    
    def __repr__(self):
        return (f"MarketEvent(timestamp={self.timestamp}, symbol={self.symbol}, "
                f"close={self.close:.2f})")


class SignalEvent(Event):
    """
    Represents a trading signal generated by a strategy.
    Indicates whether to go long, short, or exit a position.
    """
    
    def __init__(self, timestamp, symbol, signal_type, strength=1.0):
        """
        Initialize a SignalEvent.
        
        Args:
            timestamp: datetime when the signal is generated
            symbol: ticker symbol
            signal_type: 'LONG', 'SHORT', or 'EXIT'
            strength: signal strength/confidence (0.0 to 1.0)
        """
        super().__init__(timestamp)
        self.type = EventType.SIGNAL
        self.symbol = symbol
        self.signal_type = signal_type
        self.strength = strength
    
    def __repr__(self):
        return (f"SignalEvent(timestamp={self.timestamp}, symbol={self.symbol}, "
                f"signal={self.signal_type}, strength={self.strength:.2f})")


class OrderEvent(Event):
    """
    Represents an order to be executed.
    Generated from signals by the portfolio management system.
    """
    
    def __init__(self, timestamp, symbol, order_type, quantity, direction):
        """
        Initialize an OrderEvent.
        
        Args:
            timestamp: datetime when the order is placed
            symbol: ticker symbol
            order_type: 'MARKET' or 'LIMIT'
            quantity: number of shares/contracts
            direction: 'BUY' or 'SELL'
        """
        super().__init__(timestamp)
        self.type = EventType.ORDER
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = quantity
        self.direction = direction
    
    def __repr__(self):
        return (f"OrderEvent(timestamp={self.timestamp}, symbol={self.symbol}, "
                f"{self.direction} {self.quantity} shares, {self.order_type})")


class FillEvent(Event):
    """
    Represents a completed order execution.
    Contains information about the actual fill price and costs.
    """
    
    def __init__(self, timestamp, symbol, exchange, quantity, direction, 
                 fill_cost, commission=None):
        """
        Initialize a FillEvent.
        
        Args:
            timestamp: datetime when the order was filled
            symbol: ticker symbol
            exchange: exchange where the order was filled
            quantity: number of shares/contracts filled
            direction: 'BUY' or 'SELL'
            fill_cost: actual price per share at fill
            commission: transaction commission cost
        """
        super().__init__(timestamp)
        self.type = EventType.FILL
        self.symbol = symbol
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_cost = fill_cost
        self.commission = commission if commission else self.calculate_commission()
    
    def calculate_commission(self):
        """
        Calculate commission cost.
        Simple model: $1 per trade + $0.01 per share.
        """
        return 1.0 + 0.01 * self.quantity
    
    def __repr__(self):
        return (f"FillEvent(timestamp={self.timestamp}, symbol={self.symbol}, "
                f"{self.direction} {self.quantity} @ ${self.fill_cost:.2f})")
